### ISSUE TITLE
Are keys one time use?

### ISSUE THREAD

**Issue by TheGame2500** [SGrondin/bottleneck#57] opened 2018-03-19 09:51 UTC
```
Mon Mar 19 2018 11:50:35 GMT+0200 (EET) - error: (node:45466) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 56): Error: Bottleneck limiter (id: 'group-key-nuifj9q6emDxWdXAp') could not find the Redis key it needs to complete this action (key 'b_group-key-nuifj9q6emDxWdXAp_settings'), was it deleted? Note: This limiter is in a Group, it could have been garbage collected.
```

I get what is happening. But does this mean a group key is one time use? Why doesn't bottleneck just reinitialise keys after garbage collection?

**Comment by SGrondin** [comment] 2018-03-19 15:27
This is happening because you stored the results of `group.key( ... )` into a variable. A group is aware of which limiters already exist (in which case it just returns it) and which need to be created (in which case it creates it then returns it). When you use a limiter directly without calling `group.key( ... )` each time, you may be run using a limiter that has been garbage-collected.

I agree that it needs some work. It'll be improved in `2.3.0`, along with `.ready()`. I want all of that stuff to be fully transparent to the user. For the time being, when using groups, make sure to call `group.key( ... ).whatever( ... )` every time instead of `limiter.whatever( ... )`.

**Comment by SGrondin** [comment] 2018-03-20 14:37
It's a bug and at the moment the only way to make your use case work with Clustering is to call
```js
group.updateSettings({ timeout: someVeryLargeNumberOfMilliseconds })
```
to essentially disable garbage collection 😞 

I'll have it fixed within a few days. Sorry about this.

**Comment by SGrondin** [comment] 2018-03-24 17:59
`2.2.2` has been released, which includes a fix for this issue. You don't have to use any workarounds, it'll now work as intended. The combination of Group+Clustering is powerful, but it's not an easy one to design correctly. Thank you for the bug report, and for helping to make Clustering better.

**Closed by SGrondin** 2018-03-24 17:59 UTC
