### ISSUE TITLE
How to clear the queue?

### ISSUE THREAD

**Issue by roccomuso** [SGrondin/bottleneck#60] opened 2018-03-28 10:30 UTC
What's the best way to clear the queue?

**Comment by TheGame2500** [comment] 2018-03-28 10:59
@roccomuso it seems like there's no API method to do this. Note that already executing jobs can't be cancelled because there's no possibility of function execution stopping in javascript. The best way to do this seems to be
```javascript
// set max number of jobs to be 0 and strategy to be a leaky bucket, this should drop all currently non-executing jobs

limiter.updateSettings({
    highWater: 0,
    strategy: Bottleneck.strategy.LEAK,
})

// reset to initial settings
limiter.updateSettings({
    highWater: null,
    strategy: Bottleneck.strategy.YOUR_INITIAL_STRATEGY,
})
```

Also noteworthy: if you don't set a strategy, the default is `Bottleneck.strategy.LEAK` so you don't need the `strategy` param at all.

Probably needs testing, but should work, according to

https://github.com/SGrondin/bottleneck/blob/13e1d6cd2ea20e9154e1e6934da939a1a83ca396/test/general.js#L242

@SGrondin probably worth updating the limiter API or the docs for this.

**Comment by roccomuso** [comment] 2018-03-28 12:21
I did a fews tests. It doesn't seem to discard jobs neither clear the queue.

**Comment by SGrondin** [comment] 2018-03-29 18:14
There used to be an API to do this in v1, but it had subtle side effects and so it was removed for v2.  I agree it would be useful to reintroduce this feature, assuming all the quirks and side effects can be handled.

I've been prototyping what it would look like and if you're feeling brave (make sure you test your app thoroughly before using this code in production!), you can try it right now:
```js
const Bottleneck = require('bottleneck');

// This must be executed before you create any limiters!
Bottleneck.prototype.disable = function () {
  this._store.__register__ = () => { return { success: false }; }
  this._store.__running__ = () => { return Promise.resolve(0); }
  this.submit = () => { return Promise.resolve(true); }
  this._queues = this._makeQueues()
  for (var key in this._executing) {
    clearTimeout(this._executing[key].timeout)
    clearTimeout(this._executing[key].expiration)
  }
}
```
It will not work if you're using Clustering. I'll update this Issue once `disable()` is officially released. Your feedback will be useful in the development of this feature.

**Comment by roccomuso** [comment] 2018-04-04 15:24
Your solution seems to work.

What if i'd like only to clean the queue?
Could be this enough and safe?

`this._queues = this._makeQueues()`

**Comment by SGrondin** [comment] 2018-04-04 17:04
>What if i'd like only to clean the queue?
Could be this enough and safe?

It's safe, yes, but:
1. it will still run the jobs that are scheduled but not started yet
2. it will not clear the jobs that were added to the queue within the same event loop cycle
3. it will let you add more jobs to the queue afterwards

Lemme know if you'd like more details about 1. and 2.

**Comment by SGrondin** [comment] 2018-06-11 14:42
`v2.5.0` is almost complete and contains a brand new shiny `limiter.stop()` method. At this point this issue is a duplicate of #63 so I'm closing it.

If you'd like to try out the new `stop()` feature and provide feedback, you can refer to [this comment](https://github.com/SGrondin/bottleneck/issues/63#issuecomment-396079751).

**Closed by SGrondin** 2018-06-11 14:42 UTC
Labels: feature-request, in progress, question

**Comment by SGrondin** [comment] 2018-06-16 19:07
`v2.5.0` has been released with the new `stop()` method. 🎉 😄 Feedback is appreciated!
