### ISSUE TITLE
Jobs immediately timing out?

### ISSUE THREAD

**Issue by swayam18** [SGrondin/bottleneck#77] opened 2018-07-20 12:44 UTC
We are getting sporadic timeouts on jobs that were _just_ scheduled. This is what we see on our server logs:

July 20th 2018, 19:54:15.781	[Job 2391]: Started job
July 20th 2018, 19:54:16.498	[Job 2391]: Job timed out after 180000 ms.

I.e. The job failed with a timeout within 800ms even though the timeout is set to be 180s.

I have chained two rate limiters, one clustered and one local as follows:
```js
const clusterRateLimiter = new Bottleneck({
    id: 'cluster-limiter',
    minTime: 1000
    datastore: 'redis',
    clearDatastore: false,
    clientOptions: {
        ...REDIS_CREDENTIALS
    }
});

const localRateLimiter = new Bottleneck({
    maxConcurrent: 10
}).chain(clusterRateLimiter);
```

The goal is to have a local rate limit of max 10 concurrent jobs and a global rate limit of 1 per second. Each job has an expiration of 3 minutes. Am I doing something wrong here?

**Comment by SGrondin** [comment] 2018-07-26 22:42
This might be related to an issue with Redis connections that I'm currently investigating. You don't seem to be doing anything wrong from what I can tell. I'll report back as soon as I have more information.

**Comment by swayam18** [comment] 2018-07-30 17:45
Thank you, looking forward to your fix

**Comment by SGrondin** [comment] 2018-08-05 00:55
While working on #74 and #66 one of my tests started consistently failing in a way that perfectly matches what you're seeing here. Assuming it's the same issue you're experiencing, it will be fixed in v2.7.0, to be released in a few days.

**Comment by SGrondin** [comment] 2018-08-11 17:01
The bug was due to the Redis key TTL for the limiter being sometimes incorrectly set to a negative value, which would clear your limiter's internal state, which would expire running jobs immediately.

The bug is only triggered when users are using all of the following features together: Groups, Clustering, job expirations and highWater.

It was caused by a relative time - e.g. 100ms from now - being used as an absolute time (timestamp), which lead to a negative TTL value (a time in the past).

**Comment by SGrondin** [comment] 2018-08-12 19:36
v2.7.0 has just been released, please reopen this issue if it didn't fix your problem.

**Closed by SGrondin** 2018-08-12 19:36 UTC
Labels: bug, in progress

**Comment by swayam18** [comment] 2018-08-13 08:14
Thanks Simon for the effort,

I'll upgrade and let you know if I see the same issue.

**Comment by SGrondin** [comment] 2018-08-13 14:36
Thanks, I'm closely watching Github issues since this version is a major upgrade.
